### PR TITLE
release: Support multiple distributions in release-debian

### PR DESCRIPTION
**Pull request by stefwalter**
Support multiple distributions in release-debian and start building both unstable and jessie distributions during the release.

Depends on:

* [x] #59 
* [x] #58 
* [x] #52

### CODE REVIEW

**Comment by dperpeet** [comment]
needs a rebase

**Comment by stefwalter** [comment]
```
$ sudo make release-shell
...
$ release-source -f _release/source
...
$ release-dsc -f _release/source -s tools/debian/control -p _release/dsc
...
$ release-debian -p _release/dsc fedorapeople.org:/project/cockpit/debian unstable jessie
...
ERROR: 'debian-apt.jVGUeH/jessie/cockpit_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: e795fd6ab57175cfbf45b2ae90128c79, got: 35357a7e7579cf822c79eb9611b8605d
sha1 expected: 966ca3c630c5b609725104490763e5a1865d54bf, got: c3e683525bbb34c93c29ee1ef0d9385ad648b326
sha256 expected: b706fcd96c0a400c527a7311a71788728a054b95adf4c63bd881a2b305c802f1, got: ce6cbe8dc10236a8c66b338468aa7815db99e18ba2b82d36c1377ac9eccdca8f
size expected: 10728, got: 10810
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-bridge_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-bridge_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: bac19e5587a530cee9f9c43feba7b7a9, got: 0c45df2260dae391ea61dba78c6b54c7
sha1 expected: cb5baab2a4693e95cbffbc0128d45a06d0a10772, got: 02f76865bcc12baad543dfd846453e1143d6fd90
sha256 expected: 2c24e4436fb4ef5a47e1af9a1a76aae4525352f615a8b0f0d448a4787affbba4, got: f25edf62f46385220dbb2231b4194401ad2c0a7ec566cdf2414736e6f990b2de
size expected: 402482, got: 397126
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-doc_124-0_all.deb' cannot be included as 'pool/main/c/cockpit/cockpit-doc_124-0_all.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: c9240cd2a92cb8f1800e3d86d56d5c04, got: dbf18aa90e61970d1f23ffeb680a8d74
sha1 expected: 7994e795bb0717673148ea2f184e1695c98ef64e, got: 32afc6a88281f31769a4fcefcf287fae144961bf
sha256 expected: 881a40782e153121268fc6d88daeeffbffb1941aa98624c9c7b490c1e9ace086, got: fedd09f28cc1e317bb80ca5c6f50f8ccbebc5b0b8efe2db868a0238806c61d23
size expected: 288968, got: 290778
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-docker_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-docker_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 568198b792ccc1df01f3e1f775c11c19, got: a1d22f673a2553466e6a59ec8936a0b7
sha1 expected: 185d115052d4a6b3076363b852973491c999f9c7, got: 5090a541c3b047503764125a40ca564b4f4dd4f8
sha256 expected: 54ee9033350eb58fdd34058b6d39c4710dd45bb682724d22fc769f1023c4b217, got: f9b29135fed750873b90019dd959662db82967bbc0a6af14c95b6c1283bc1cd7
size expected: 231000, got: 231376
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-machines_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-machines_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: a78153c3e5e83a81a13d69a9316e9d23, got: b5f2727cb39e6830dd3117abc04ccca8
sha1 expected: 95c818f26506e9cf116075f5500c8297694da62f, got: 46a4bfbff8e937df05fe030ef48672553db3455f
sha256 expected: 43dcd2fa2ec96626f2bfed8c56d879997e0e424264719e24574eaf583cb67932, got: 2bcc8901e392023c264f3eb96851eaa8914425e745de3cb21871c872090b15e0
size expected: 141684, got: 141726
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-networkmanager_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-networkmanager_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 128cc5b9d3981740f5ff6700eb00d603, got: 6ea1651699b28fe35667db308dae7187
sha1 expected: 5a4a571314ca37ebd2a37c489a486c59e36217ff, got: 91d436ad6d53e2b16c4f5c7e7660638084af873e
sha256 expected: 1586dd4878e10182010147d0da68ed4567caa93ef4032636ea095631e51daecd, got: 7544cd7591a6b81b74402ed4c5af821e2b8f0cdaec2a60b9e49f49f6b7ad0c47
size expected: 56874, got: 56928
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-pcp_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-pcp_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: ccb7413dbc829a9544c3b47f308b4ac8, got: a7ad91ff7c2e53ac1e48abf8cb978317
sha1 expected: 0932ed141ff4facd68b1673a4269345ab92832ae, got: 752885eff831cbfd175bfbf612c69239c3b7b6a7
sha256 expected: 5047f17d203564542902e61cc980a5e9a0fb9196e593ceec61d6d425ed104b06, got: d1374e79780b996ed3cc2ce73893eefe2075d6b7e6b40d4f7eaf05b5ad7ae516
size expected: 42460, got: 40560
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-shell_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-shell_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 109993094b784a488a31c88b746a72d7, got: 35abba88c09235435b8c5d2286538c0e
sha1 expected: 1259f30b3bbb074f0ae81caa36b460e2ad0f0d75, got: 4b3f46d98cb3613855e6bee6eddd526ae1898eb5
sha256 expected: c0fb289009f5012bc28f15a33ead99a2c1b8bc4620c991133cdb352aa03e6e3d, got: 932a85c7be2dcea8a18bd848929450c5d0b2b83919b5e716bcea1817cef6c3ad
size expected: 586420, got: 586542
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-storaged_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-storaged_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 7664697e79daad8577a61849b963b067, got: 96c27926e71569be9872d8f54d05c0cd
sha1 expected: 2ecca9e13ffe6c2b129e8964457cc2f55f2c833b, got: 63cff59b78fe682b14fc00810f1fa07c69c5966d
sha256 expected: 00d0a033d25ada17db9c5b54f11130d2a2bc569440f4c1d7f4de647b78bfaf0c, got: 89335194735fefdf6e04a7da693e7cfa508bd36e91b4b1ef171af86190d72409
size expected: 87492, got: 87572
ERROR: 'debian-apt.jVGUeH/jessie/cockpit-ws_124-0_amd64.deb' cannot be included as 'pool/main/c/cockpit/cockpit-ws_124-0_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 8bd9d01180d236998e742e68540e024c, got: 92e5f5a4cf8581ef47690117e03b8157
sha1 expected: 383552dc25382f46454a90e76affd505fd7d2a7b, got: d064fffee6a9eae21bbb54eb0a702781483ac7ba
sha256 expected: 8bc64aa360b2a4b0b6e042c30f25094ca7e6c0df5629a148f747e6056390ff8e, got: 8e172944875dcf904c2980d2832c64c37fc80c4c3d7cb8ca7272f9a0c8e1acd2
size expected: 388916, got: 384486
There have been errors!
```

**Comment by larskarlitski** [comment]
Not sure what the "proper" solution here is. My best idea is to encode the distribution name into the version, for example `cockpit_124-0jessie_amd64.deb`. That would mean that we'd have to build the `.dsc` file for every distribution again, because the version is set in the `changelog`.

What do you think?

**Comment by stefwalter** [comment]
@larskarlitski Can we have different repository directories and use a variable like $distribution or $version in the /etc/apt/sources.list file (or whatever)?

**Comment by larskarlitski** [comment]
Yes, that's another option: add the package to two completely separate repositories.

**Comment by stefwalter** [comment]
> Yes, that's another option: add the package to two completely separate repositories.

Yes that should work. Bonus points for:
 * Making an upgrade work properly by having a variable in sources.list that adapts during the upgrade.
 * Making the running.html instructions simple by having a single line to paste into sources.list irregardless of Jessie or Unstable.

**Comment by larskarlitski** [comment]
Do you mean upgrades for the same version? As far as I know, it already works when we release a new version of cockpit.

I'm afraid the second one won't work. Having two repositories means that they will be in different paths on fedorapeople.org.

**Comment by stefwalter** [comment]
> I'm afraid the second one won't work. Having two repositories means that they will be in different paths on fedorapeople.org.

And there's no variable expansion in sources.list?

**Comment by dperpeet** [comment]
needs rebase

**Comment by stefwalter** [comment]
Rebased.

**Comment by larskarlitski** [comment]
Appending the distribution's codename to the package's version works for me. Commit is at  [04d2f7d2](https://github.com/larskarlitski/cockpituous/commit/04d2f7d2c4974339b0e5fca09a3c2c585a4def2d). I'm not sure if I should push it here or if you prefer cherry-picking it.

It's a bit annoying to have to unpack, sed, and repack the .dsc, but that seems to be the sanest way of achieving this.

**Pull request closed without merging**
