### PR TITLE
Add fedora-logos in the Dockerfile

### PR DESCRIPTION
**Pull request by KKoukiou**
Needed by anaconda-webui RPM.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks! I'll trigger a build, but these refreshes tend to break pixel tests and such, so we'll need to work through all our projects tomorrow. But that's ok.

**Comment by martinpitt** [comment]
Triggered a build: https://github.com/cockpit-project/cockpituous/actions/runs/6893507798 . This will trickle into the bots by tomorrow, but I can also make sure to re-deploy it synchronously.

**Comment by martinpitt** [comment]
@KKoukiou While it's harmless, I still wonder why -- shouldn't this be a *runtime* dependency, not a build-time one? And even if it's a build-time one, build should happen in a VM, not on the host. You'd *never* rpm-install anaconda-webui.rpm inside the tasks container.

I refreshed my local cockpit/tasks toolbox with this rebuild, and locally ran the podman tests on f39.

**Comment by martinpitt** [comment]
I rolled this out as it doesn't seem to cause too many regressions (and I hope these are naughties), and it's good to refresh the container from time to time anyway. So you should be unblocked, but please fix the build/binary dependencies of this. Not landing yet, until we discussed that.

**Comment by KKoukiou** [comment]
You 're right, build is happening in the VM, this is not needed.

**Pull request closed without merging**
