### PR TITLE
tasks: Update to Fedora 33

### PR DESCRIPTION
**Pull request by martinpitt**
- CentOS CI [successful](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14913-20210112-092157-7de669da-fedora-coreos/log.html) [tests](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14913-20210112-092154-7de669da-ubuntu-2004/log.html)
 - [firefox on e2e](https://logs.cockpit-project.org/logs/pull-15125-20210112-095932-b037f913-fedora-32-firefox/log.html) successful test
 - [RHEL on e2e](https://logs.cockpit-project.org/logs/pull-15125-20210112-095932-b037f913-rhel-8-4/log.html) successful test

### CODE REVIEW

**Comment by martinpitt** [comment]
[built in workflow](https://github.com/cockpit-project/cockpituous/actions/runs/462830829) which [pushed it to quay](https://quay.io/repository/cockpit/tasks?tab=tags). I tested the container interactively on e2e, and it generally works. I deployed the new container on e2e (CentOS CI is down ATM).

**Comment by martinpitt** [comment]
Getting some [weird failures](https://logs.cockpit-project.org/logs/pull-164-20210105-074358-dfb5541a-fedora-coreos/log.html), I rolled back for now.

**Comment by martinpitt** [comment]
I am having another go at this, and set :latest back to the F33 build from a week ago. An interactive container on cockpit-7 with a simple cockpit clone and `./autogen.sh && make` works fine, but all [e2e tests fail](https://logs.cockpit-project.org/logs/pull-14913-20210112-091433-7de669da-fedora-32/log.html) like:
```
I am going to run ./configure with no arguments - if you wish 
to pass any to it, please specify them on the ../autogen.sh command line.
bots/ already exists, skipping
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
```
This does not happen on a [CentOS CI run](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14913-20210112-092147-7de669da-fedora-32/log.html).

At first sight this smells like a weird f-33-docker-on-RHEL-7 incompatibility, which we already had in other cases (stat failure in a container due to some seccomp issue). But that old one was pretty obvious and happened in an interactive container.

**Comment by martinpitt** [comment]
I added a workaround, deployed it, and posted links to the description with successful test runs. I also rebuilt my local cockpit/tasks based toolbox, it works fine.

**Review by Gundersanne — APPROVED** [review]
Hm could there also be a workaround using a seccomp profile where fstat is allowed? Not sure if it's worth it though.

If not and if it's too much bother, lgtm :)

**Comment by martinpitt** [comment]
@Gundersanne : I haven't found any, I'm afraid.. But honestly I think the UID isolation is more than enough, we run everything as unpriv user in the container.

**Pull request merged**
