### PR TITLE
Rename welder-web to cockpit-composer

### PR DESCRIPTION
**Pull request by larskarlitski**
The upstream name changed.

### CODE REVIEW

**Comment by martinpitt** [comment]
@larskarlitski : Are you going to rebuild/push the container? Or need help with that? I can definitively help with the rollout on the BOS side, @Gundersanne or me can roll it out on centosci.

**Comment by larskarlitski** [comment]
> @larskarlitski : Are you going to rebuild/push the container? Or need help with that? I can definitively help with the rollout on the BOS side, @Gundersanne or me can roll it out on centosci.

I've updated and am pushing the container. Wanted to have someone approve this pull request before doing so.

I do need help with rolling it out, please. Thanks!

**Comment by martinpitt** [comment]
I rolled out the new container everywhere. The webhook now crashes:
```
ERROR:root:tests-scan: Error accessing /repos/weldr/welder-web/pulls?page=1&per_page=100&state=open&sort=created&direction=desc

Response: {"message":"Moved Permanently","url":"https://api.github.com/repositories/69981456/pulls?page=1&per_page=100&state=open&sort=created&direction=desc","documentation_url":"https://developer.github.com/v3/#http-redirects"}

subprocess.CalledProcessError: Command '['bots/tests-scan', '--amqp', 'amqp.cockpit.svc.cluster.local:5671']' returned non-zero exit status 1. 
```

So bots/tests-scan is somehow being redirected to the old one, or it's because https://github.com/cockpit-project/cockpit/pull/11835 wasn't landed yet? I'll try landing it and restarting.

**Comment by martinpitt** [comment]
Rolled out everywhere.

**Comment by martinpitt** [comment]
[log from centosci](https://209.132.184.41:8493/logs/pull-11813-20190515-164343-8c537c1f-weldr-cockpit-composer-cockpit-fedora-29-chrome/log), looks :+1:

**Comment by martinpitt** [comment]
Please check if these get reasonably far:

[composer log on bos](https://209.132.184.41:8493/logs/pull-11813-20190515-161111-8c537c1f-weldr-welder-web-cockpit-rhel-8-1-chrome/log)

[cockpit log on bos](https://209.132.184.41:8493/logs/pull-11545-20190515-164343-2ab1cdbf-verify-fedora-29/log.html)

**Pull request merged**
