### PR TITLE
tasks: Introduce environment variables for bots repo/branch

### PR DESCRIPTION
**Pull request by martinpitt**
This will allow us to regression-test a bots PR with run-local.sh.

### CODE REVIEW

**Comment by martinpitt** [comment]
tests are green, so I [rebuilt the container](https://github.com/cockpit-project/cockpituous/actions/runs/531031523) and rolled it out everywhere. Waiting for some test results now.

**Comment by martinpitt** [comment]
Successful tests:
 - [chrome test](https://logs.cockpit-project.org/logs/pull-15263-20210202-145226-602cbdd9-rhel-8-4-distropkg/log.html)
 - [firefox test](https://logs.cockpit-project.org/logs/pull-15256-20210202-145547-24888bc4-fedora-32-firefox/log.html)

Unblocking, ready for review.

**Comment by martinpitt** [comment]
Updated to also let run-local.sh know that new environment. Tested locally with

    COCKPIT_BOTS_REPO=https://github.com/martinpitt/bots COCKPIT_BOTS_BRANCH=bots-local-unit-test tasks/run-local.sh

(to test bots from https://github.com/cockpit-project/bots/pull/1622). This does not change the container image, so no rebuild necessary.

**Review by marusak — APPROVED** [review]
Nice, thanks!

**Pull request merged**
