### PR TITLE
tasks: Add python3-pillow and s3-keys symlink 

### PR DESCRIPTION
**Pull request by mvollmer**
For upcoming pixel tests.

### CODE REVIEW

**Comment by martinpitt** [comment]
Looks good of course -- but as usual, setting blocked until we get a few successful runs with the refreshed containers.

@mvollmer: Once the integration test succceds, [build the tasks container](https://github.com/cockpit-project/cockpituous/actions/workflows/build-tasks.yml) against this branch, and then yell at @Gundersanne or me to deploy it. However, please coordinate with @allisonkarlitskaya -- she was working on some changes also, and it may make sense to rebuild/redeploy/test this just once.

**Review by martinpitt — APPROVED** [review]

**Comment by mvollmer** [comment]
`build-tasks` has completed: https://github.com/cockpit-project/cockpituous/actions/runs/632497356

**Comment by martinpitt** [comment]
I turned the maintenance/deploy-tasks-container.yml crank, all bots run the new tasks. Now go and find a nice cockpit PR to test, to make sure that the refresh didn't break anything (in particular, new firefox/chromium versions).

**Comment by martinpitt** [comment]
Last night's image refreshes went well, unblocking.

**Pull request merged**
