### PR TITLE
aws: Drop image mirror

### PR DESCRIPTION
**Pull request by martinpitt**
The main purpose of this was to provide a backup if e2e goes down. But
with images primarily living on S3 now, the e2e machines (like
cockpit-11) now *are* the backup.

https://github.com/cockpit-project/bots/commit/8e52fe595e dropped this
AWS mirror, so decomission it.

### CODE REVIEW

**Comment by martinpitt** [comment]
Le huh, that's entirely new now.. 
```
+ ./image-prune
image-prune: Error accessing /repos/cockpit-project/bots/pulls?page=1&per_page=100&state=open&sort=created&direction=desc
  Status: 401
  Reason: Unauthorized
```
That still worked fine until a few days ago.. This will need a debugging session.

**Review by allisonkarlitskaya — APPROVED** [review]
:+1: 

Not sure if you want to block on the unrelated fail or not...

**Comment by martinpitt** [comment]
@allisonkarlitskaya : *of course*! This is PR #403, so *naturally* it must get a permission denied :grin: 

I'll investigate the failure in PR #404 instead (if I can ever find it)

**Comment by martinpitt** [comment]
Yep, #404 failed in the same way.

**Comment by martinpitt** [comment]
I removed the AWS instance and network interface, and @sgallagh removed the internal-images DNS entry.

**Pull request merged**
