### PR TITLE
webhook: Reduce amqp logging level

### PR DESCRIPTION
**Pull request by Gundersanne**

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Is it now better readable? :)

**Comment by Gundersanne** [comment]
Yea but nothing relevant coming out sadly :(

Just these on startup:
```
operation queue.declare caused a channel exception not_found: no queue 'statistics' in vhost '/'
2020-10-21 10:27:22.423 [error] <0.978.0> Channel error on connection <0.970.0> (10.128.6.1:47322 -> 10.131.2.187:5671, vhost: '/', user: 'cockpit-amqp'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'statistics' in vhost '/'
```

**Comment by marusak** [comment]
I guess we cannot get who requested what message from it, right?

**Comment by Gundersanne** [comment]
Well we can get the ip of the client but since it's forwarded from a OC router it's meaningless :p

**Pull request merged**
