### PR TITLE
tasks: Update to Fedora 35, downgrade Chromium to 93

### PR DESCRIPTION
**Pull request by martinpitt**
See https://bugzilla.redhat.com/show_bug.cgi?id=2013095

I built this locally and created a toolbox out of this. This works quite fine for starter-kit, machines, and cockpit itself, so I think it's ready.

 - [x] https://github.com/cockpit-project/starter-kit/pull/501
 - [x] https://github.com/cockpit-project/cockpit-machines/pull/422
 - [x] https://github.com/cockpit-project/cockpit-podman/pull/794
 - [x] https://github.com/osbuild/cockpit-composer/pull/1366
 - [x] https://github.com/candlepin/subscription-manager/pull/2831
 - [x] https://github.com/cockpit-project/cockpit/pull/16451
 - [x] https://github.com/cockpit-project/cockpit/pull/16452
 - [x] https://github.com/cockpit-project/cockpit/pull/16457
 - [x] fix cockpit for npm 7: https://github.com/cockpit-project/cockpit/pull/16469
 - [x] https://github.com/cockpit-project/cockpit-ostree/pull/203

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Thanks, nothing against, please roll it out and lets see if CI is happy about it

**Comment by martinpitt** [comment]
All "fix for NPM 7" PRs landed now, so I [rebuilt the container](https://github.com/cockpit-project/cockpituous/actions/runs/1335975490), and gave it a quick manual test on an e2e machine (new glibc and all..). I rolled out the new container everywhere, now waiting for some test results.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/16456 ran with the new container, and [firefox clearly has problems](https://logs.cockpit-project.org/logs/pull-16456-20211013-055745-e942318f-fedora-34-firefox/log.html). I reverted the `:latest` tag and rolled back the infra.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/16479 has chromium and firefox successes, and in https://github.com/cockpit-project/cockpit/pull/16480 there are successful runs on CentOS CI, so this is finally working. Still waiting for the ostree fix to land.

**Pull request merged**
