### PR TITLE
tasks: Use a different Firefox 69 build

### PR DESCRIPTION
**Pull request by martinpitt**
The previous one does not exist any more.

### CODE REVIEW

**Comment by martinpitt** [comment]
Container rebuilt, pushed, rolled out. Need to wait for a few successful results.

**Comment by martinpitt** [comment]
Meh, that apparently [did not work](https://logs.cockpit-project.org/logs/pull-771-20200420-090245-c523f840-fedora-31-firefox-cockpit-project-cockpit/log.html#2-2)

**Comment by martinpitt** [comment]
The fc32 build doesn't work on F30, fails with an unresolved symbol. So I added an extra symlink into $PATH. Rebuilt, rolled out, tasks restarted.

**Comment by martinpitt** [comment]
[cockpit tests](https://logs.cockpit-project.org/logs/pull-771-20200420-094909-c523f840-fedora-31-firefox-cockpit-project-cockpit/log.html) now work, and [composer/firefox tests](https://logs.cockpit-project.org/logs/pull-771-20200420-094927-c523f840-fedora-31-firefox-osbuild-cockpit-composer/log.html) look generally okay as well.

**Comment by marusak** [comment]
> composer/firefox tests look generally okay as well.

but that is selenium test, so it does not use this firefox browser.

**Comment by martinpitt** [comment]
Darn -- the new container subtly changed something in locale configuration -- e. g. [this](https://logs.cockpit-project.org/logs/pull-13927-20200420-102833-880df459-debian-stable/log.html) or [this](https://logs.cockpit-project.org/logs/pull-13921-20200420-103756-9ef83fe0-debian-stable/log.html) log. The debian images are known to not have any non-C locales. It's not obvious to me why that happens, but I think we can just fix it in cockpit's default expected messages.

**Pull request merged**
