### PR TITLE
tasks: Various fixes and improvements; add script to run AMQP+tasks locally

### PR DESCRIPTION
**Pull request by martinpitt**
I would like to make our tasks container self-testable, and run integration tests on tasks container refreshes and changes to the logic eventually. This is as far as I got today. It's not yet self-testing, but at least one can now run it locally in a very easy way. Please test it and let me know how it works for you!

### CODE REVIEW

**Comment by martinpitt** [comment]
I [refreshed the container](https://github.com/cockpit-project/cockpituous/actions/runs/496109775) and deployed it everywhere. Will link to successful test runs.

**Comment by martinpitt** [comment]
[this test](https://logs.cockpit-project.org/logs/pull-15154-20210119-140037-ddb634c7-ubuntu-stable/log.html) ran with the new container, and looks reasonable.

**Comment by martinpitt** [comment]
I'm experimenting with running this new script in a GitHub workflow. This does not change the container content, and thus does not invalidate the previous cockpit integration test results.

**Comment by martinpitt** [comment]
Cool, [works](https://github.com/cockpit-project/cockpituous/actions/runs/496400942)! Pushing again with more sensible naming. I want to also integrate `make check` into this (replacing semaphore) to have all test definitions inside of the archive. But that's for a follow-up.

**Comment by martinpitt** [comment]
I just couldn't resist and added running unit tests here, but surprisingly [it fails on GitHub](https://github.com/cockpit-project/cockpituous/pull/359/checks?check_run_id=1729194055). Our semaphore still uses a rather ancient Ubuntu 16.04. Investigating..

**Review by Gundersanne — APPROVED** [review]
Lovely! Tried it locally and honestly this is great. Can't wait for an easy way to produce workloads/post stuff to the queue :)

**Pull request merged**
