### PR TITLE
tasks: Fix build, drop unnecessary packages

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
I built the container locally and ran `bots/image-create selenium` in it to exercise all the libvirt and image create stuff. I [pushed the container image](https://hub.docker.com/r/cockpit/tasks/tags/) and restarted tasks bots. Let's wait for some successful tests to make sure.

**Comment by martinpitt** [comment]
E. g. https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12703-20190904-084848-17e2fc80-cockpit-project-cockpit--fedora-30/log.html is running on the new container.

**Comment by martinpitt** [comment]
@Gundersanne: Test passed, so unblocking. This is ready to land.

**Comment by Gundersanne** [comment]
@martinpitt Should I squash and add the closes? Otherwise this needs another forcepush.

**Comment by martinpitt** [comment]
@Gundersanne : Oh right, sorry! I added the Closes #. Semaphore is super-fast here, so let's just do this properly.

**Pull request merged**
