### PR TITLE
tasks: Drop .tasks file support

### PR DESCRIPTION
**Pull request by martinpitt**
All projects moved away from .tasks to GitHub workflows.

### CODE REVIEW

**Comment by martinpitt** [comment]
I did *not* build a container with this. I think @Gundersanne wants to land #346 and possibly #341 first, and this is not at all urgent. I just wanted to stash it so that we don't forget to clean it up.

**Comment by martinpitt** [comment]
Unblocking. There has been no movement on the other two PRs, and removing this code may help the others to become easier.

**Comment by martinpitt** [comment]
Oops, putting back blocked -- we should first build/roll out a container before landing this, but I'd like to get a review/ack first.

**Review by Gundersanne — APPROVED** [review]
This should work I think

**Comment by martinpitt** [comment]
Just rebased to current master to make container build more convenient/robust.

I pushed and rolled out the container, let's give it some time to prove that it works.

**Comment by martinpitt** [comment]
https://logs.cockpit-project.org/logs/pull-14854-20201103-102218-c0f44c18-fedora-32-firefox/log.html and https://logs.cockpit-project.org/logs/pull-14854-20201103-102205-c0f44c18-fedora-coreos/log.html ran with the new container, and the webhook container works fine.

**Pull request merged**
